import { lazy } from "react";

export const PAGE_MAP = {
  home: lazy(() => import("../pages/My_Home")),
  filebrowser: lazy(() => import("../pages/My_FileBrowser")),
  splittable: lazy(() => import("../pages/My_SplitTable")),
  lotmanage: lazy(() => import("../pages/My_LotManagement")),
  ramcache: lazy(() => import("../pages/My_RamCache")),
  matchfill: lazy(() => import("../pages/My_MatchFill")),
  dashboard: lazy(() => import("../pages/My_Dashboard")),
  chartbuilder: lazy(() => import("../pages/My_ChartBuilder")),
  templatereport: lazy(() => import("../pages/My_TemplateReport")),
  autoreport: lazy(() => import("../pages/My_AutoReport")),
  lotrequest: lazy(() => import("../pages/My_LotRequest")),
  diagnosis: lazy(() => import("../pages/My_Diagnosis")),
  tracker: lazy(() => import("../pages/My_Tracker")),
  valve: lazy(() => import("../pages/My_ValveAlerts")),
  teg: lazy(() => import("../pages/My_TegMap")),
  yieldmap: lazy(() => import("../pages/My_YieldMap")),
  ettime: lazy(() => import("../pages/My_EtTime")),
  inform: lazy(() => import("../pages/My_Inform")),
  reformatize: lazy(() => import("../pages/My_Reformatize")),
  dcop: lazy(() => import("../pages/My_DcopCheck")),
  calendar: lazy(() => import("../pages/My_Calendar")),
  meeting: lazy(() => import("../pages/My_Meeting")),
  tablemap: lazy(() => import("../pages/My_TableMap")),
  devguide: lazy(() => import("../pages/My_DevGuide")),
  admin: lazy(() => import("../pages/My_Admin")),
};
