#!/usr/bin/env python
"""Standard setuptools packaging script for the Flow app.

WHY NOT `setup.py`?
    The file named `setup.py` in this repo is NOT a packaging script — it is a
    large (multi-MB) self-contained installer bundle generated by
    `_build_setup.py`. It embeds the whole source tree as gzip+base64 blobs and
    preserves user data when re-run. Overwriting it would break the release
    workflow, so the standard packaging metadata lives here instead.

USAGE
    python setup_pkg.py sdist bdist_wheel      # build a distribution
    pip install -e .                            # editable install (uses this
                                                # file only if setup.py is the
                                                # bundle; prefer requirements.txt)

    In practice, install runtime deps with:
        pip install -r backend/requirements.txt
    and dev/test deps with:
        pip install -r backend/requirements-dev.txt

Version is read from VERSION.json and dependencies from
backend/requirements.txt so this file never drifts out of sync.
"""

import json
import re
from pathlib import Path

from setuptools import find_packages, setup

HERE = Path(__file__).parent.resolve()


def read_version() -> str:
    """Read the canonical version from VERSION.json (fallback: 0.0.0)."""
    version_file = HERE / "VERSION.json"
    try:
        data = json.loads(version_file.read_text(encoding="utf-8"))
        return str(data.get("version", "0.0.0"))
    except (OSError, ValueError):
        return "0.0.0"


def read_requirements(name: str) -> list[str]:
    """Parse a pip requirements file into a list of specifiers.

    Skips blank lines, comments, and `-r other.txt` include directives
    (those are resolved by pip, not by setuptools).
    """
    req_file = HERE / "backend" / name
    reqs: list[str] = []
    try:
        lines = req_file.read_text(encoding="utf-8").splitlines()
    except OSError:
        return reqs
    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("-"):
            continue
        # Drop inline comments.
        line = line.split("#", 1)[0].strip()
        if line:
            reqs.append(line)
    return reqs


def read_long_description() -> str:
    readme = HERE / "README.md"
    try:
        return readme.read_text(encoding="utf-8")
    except OSError:
        return ""


install_requires = read_requirements("requirements.txt")

# Dev deps = requirements-dev.txt minus the `-r requirements.txt` include.
dev_requires = read_requirements("requirements-dev.txt")

setup(
    name="flow",
    version=read_version(),
    description=(
        "Fab data analytics + plan-vs-actual tracking platform for "
        "semiconductor development/pilot process data, with an AI "
        "analysis layer (Flow-i)."
    ),
    long_description=read_long_description(),
    long_description_content_type="text/markdown",
    author="goood2280",
    author_email="goood2280@gmail.com",
    url="https://github.com/goood2280/flow",
    license="Proprietary",
    python_requires=">=3.10",
    keywords=["semiconductor", "fab", "analytics", "fastapi", "data-analysis"],
    # The distributable artifact is the self-contained setup.py bundle, not a
    # wheel of importable top-level packages. Backend code lives under backend/.
    packages=find_packages(include=["backend", "backend.*"]),
    include_package_data=True,
    install_requires=install_requires,
    extras_require={"dev": dev_requires},
    project_urls={
        "Homepage": "https://github.com/goood2280/flow#readme",
        "Repository": "https://github.com/goood2280/flow.git",
        "Issues": "https://github.com/goood2280/flow/issues",
    },
    classifiers=[
        "Private :: Do Not Upload",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Framework :: FastAPI",
        "Intended Audience :: Manufacturing",
    ],
)
